name: zhwaweb
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  flutter_localizations:
    sdk: flutter
  flutter_gen: ^5.12.0
  iconsax: ^0.0.8
  http: ^1.1.0
  shared_preferences: ^2.2.2
  dio: ^5.4.0
  file_picker: ^8.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: TheYearofHandicrafts
      fonts:
        - asset: assets/fonts/TheYearofHandicrafts-Regular.otf
        - asset: assets/fonts/TheYearofHandicrafts-Medium.otf
          weight: 500
        - asset: assets/fonts/TheYearofHandicrafts-SemiBold.otf
          weight: 600
        - asset: assets/fonts/TheYearofHandicrafts-Bold.otf
          weight: 700
        - asset: assets/fonts/TheYearofHandicrafts-Black.otf
          weight: 900
